<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2013sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:ns0="urn:riv:clinicalprocess:activity:request:1" xmlns:ns1="urn:riv:clinicalprocess:activity:request:ProcessRequestOutcomeResponder:1" xmlns:ns2="urn:riv:clinicalprocess:activity:request:request" exclude-result-prefixes="xs fn ns0 ns1 ns2">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<ClinicalDocument xmlns="urn:hl7-org:v3">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance" select="'urn:hl7-org:v3 C:/Users/vije/Documents/Resources/HL7CDA~1/infrastructure/cda/CDA.xsd'"/>
			<xsl:for-each select="ns1:ProcessRequestOutcome/ns0:requestOutcome">
				<xsl:variable name="var1_requestOutcomeTime" as="node()?" select="ns2:requestOutcomeTime"/>
				<xsl:variable name="var2_resultof_first" as="node()" select="ns2:outcome"/>
				<xsl:variable name="var3_resultof_first" as="node()" select="ns2:requestId"/>
				<xsl:variable name="var4_resultof_first" as="node()" select="ns2:author"/>
				<xsl:variable name="var5_resultof_first" as="node()" select="ns2:requestOutcomeId"/>
				<xsl:variable name="var6_resultof_first" as="node()" select="ns2:patient"/>
				<xsl:variable name="var7_resultof_first" as="node()" select="$var6_resultof_first/ns2:personId"/>
				<xsl:variable name="var8_resultof_first" as="node()" select="$var4_resultof_first/ns2:healthcareProfessional"/>
				<xsl:variable name="var9_resultof_first" as="node()" select="ns2:recipient/ns2:organisation/ns2:careUnitId"/>
				<xsl:variable name="var10_resultof_first" as="node()" select="$var4_resultof_first/ns2:healthcareProfessionalOrganisation/ns2:careUnitId"/>
				<xsl:attribute name="classCode" namespace="" select="'DOCCLIN'"/>
				<xsl:attribute name="moodCode" namespace="" select="'EVN'"/>
				<typeId>
					<xsl:attribute name="root" namespace="" select="'2.16.840.1.113883.1.3'"/>
					<xsl:attribute name="extension" namespace="" select="'POCD_HD000040'"/>
				</typeId>
				<id>
					<xsl:attribute name="root" namespace="" select="fn:string($var5_resultof_first/@root)"/>
					<xsl:attribute name="extension" namespace="" select="fn:string($var5_resultof_first/@extension)"/>
				</id>
				<code>
					<xsl:attribute name="code" namespace="" select="fn:string(ns2:typeOfRequestOutcome/@code)"/>
					<xsl:attribute name="codeSystem" namespace="" select="'1.2.752.129.2.2.2.20'"/>
				</code>
				<title>Remissvar</title>
				<xsl:for-each select="$var1_requestOutcomeTime">
					<effectiveTime>
						<xsl:attribute name="value" namespace="" select="fn:string(@value)"/>
					</effectiveTime>
				</xsl:for-each>
				<confidentialityCode>
					<xsl:attribute name="code" namespace="" select="'N'"/>
					<xsl:attribute name="codeSystem" namespace="" select="'2.16.840.1.113883.5.25'"/>
				</confidentialityCode>
				<recordTarget>
					<patientRole>
						<id>
							<xsl:attribute name="root" namespace="" select="fn:string($var7_resultof_first/@root)"/>
							<xsl:attribute name="extension" namespace="" select="fn:string($var7_resultof_first/@extension)"/>
						</id>
						<patient>
							<xsl:for-each select="$var6_resultof_first/ns2:name">
								<name>
									<xsl:sequence select="fn:string(.)"/>
								</name>
							</xsl:for-each>
						</patient>
					</patientRole>
				</recordTarget>
				<author>
					<xsl:for-each select="$var1_requestOutcomeTime">
						<time>
							<xsl:attribute name="value" namespace="" select="fn:string($var4_resultof_first/ns2:dateOfRequest/@value)"/>
						</time>
					</xsl:for-each>
					<assignedAuthor>
						<xsl:for-each select="$var8_resultof_first/ns2:id">
							<id>
								<xsl:attribute name="root" namespace="" select="fn:string(@root)"/>
								<xsl:attribute name="extension" namespace="" select="fn:string(@extension)"/>
							</id>
						</xsl:for-each>
						<code>
							<xsl:attribute name="code" namespace="" select="fn:string($var4_resultof_first/ns2:typeOfHealthcareProfessional/@code)"/>
							<xsl:attribute name="codeSystem" namespace="" select="'1.2.752.97.3.2.8.8'"/>
						</code>
						<assignedPerson>
							<name>
								<xsl:sequence select="fn:string($var8_resultof_first/ns2:name)"/>
							</name>
						</assignedPerson>
					</assignedAuthor>
				</author>
				<custodian>
					<assignedCustodian>
						<representedCustodianOrganization>
							<id>
								<xsl:attribute name="root" namespace="" select="fn:string($var10_resultof_first/@root)"/>
								<xsl:attribute name="extension" namespace="" select="fn:string($var10_resultof_first/@extension)"/>
							</id>
						</representedCustodianOrganization>
					</assignedCustodian>
				</custodian>
				<informationRecipient>
					<intendedRecipient>
						<receivedOrganization>
							<id>
								<xsl:attribute name="root" namespace="" select="fn:string($var9_resultof_first/@root)"/>
								<xsl:attribute name="extension" namespace="" select="fn:string($var9_resultof_first/@extension)"/>
							</id>
						</receivedOrganization>
					</intendedRecipient>
				</informationRecipient>
				<inFulfillmentOf>
					<xsl:attribute name="typeCode" namespace="" select="'FLFS'"/>
					<order>
						<xsl:attribute name="classCode" namespace="" select="'ACT'"/>
						<xsl:attribute name="moodCode" namespace="" select="'RQO'"/>
						<id>
							<xsl:attribute name="root" namespace="" select="fn:string($var3_resultof_first/@root)"/>
							<xsl:attribute name="extension" namespace="" select="fn:string($var3_resultof_first/@extension)"/>
						</id>
					</order>
				</inFulfillmentOf>
				<component>
					<structuredBody>
						<component>
							<section>
								<code>
									<xsl:attribute name="code" namespace="" select="'SI'"/>
									<xsl:attribute name="codeSystem" namespace="" select="'1.2.752.97.3.1.11'"/>
									<xsl:attribute name="codeSystemName" namespace="" select="'SLL Informationskomponentkoder'"/>
									<xsl:attribute name="displayName" namespace="" select="'svarsinformation'"/>
								</code>
								<title>detaljerad remissvarsinformation</title>
								<text>
									<xsl:sequence select="fn:string($var2_resultof_first/ns2:outcomeText)"/>
								</text>
								<xsl:for-each select="$var2_resultof_first/ns2:accomplishedActivity">
									<xsl:variable name="var11_resultof_first" as="node()" select="ns2:code"/>
									<xsl:variable name="var12_resultof_first" as="node()" select="ns2:id"/>
									<entry>
										<act>
											<xsl:attribute name="classCode" namespace="" select="'PCPR'"/>
											<xsl:attribute name="moodCode" namespace="" select="'EVN'"/>
											<id>
												<xsl:attribute name="root" namespace="" select="fn:string($var12_resultof_first/@root)"/>
												<xsl:attribute name="extension" namespace="" select="fn:string($var12_resultof_first/@extension)"/>
											</id>
											<code>
												<xsl:attribute name="code" namespace="" select="fn:string($var11_resultof_first/@code)"/>
												<xsl:attribute name="codeSystem" namespace="" select="fn:string($var11_resultof_first/@codeSystem)"/>
											</code>
											<text>
												<xsl:sequence select="fn:string(ns2:text)"/>
											</text>
										</act>
									</entry>
								</xsl:for-each>
								<xsl:for-each select="$var2_resultof_first/ns2:condition">
									<xsl:variable name="var13_resultof_first" as="node()" select="ns2:id"/>
									<entry>
										<observation>
											<xsl:attribute name="classCode" namespace="" select="'OBS'"/>
											<xsl:attribute name="moodCode" namespace="" select="'EVN'"/>
											<id>
												<xsl:attribute name="root" namespace="" select="fn:string($var13_resultof_first/@root)"/>
												<xsl:attribute name="extension" namespace="" select="fn:string($var13_resultof_first/@extension)"/>
											</id>
											<xsl:for-each select="ns2:code">
												<code>
													<xsl:attribute name="code" namespace="" select="fn:string(@code)"/>
													<xsl:attribute name="codeSystem" namespace="" select="fn:string(@codeSystem)"/>
												</code>
											</xsl:for-each>
											<xsl:for-each select="ns2:text">
												<text>
													<xsl:sequence select="fn:string(.)"/>
												</text>
											</xsl:for-each>
										</observation>
									</entry>
								</xsl:for-each>
							</section>
						</component>
						<component>
							<section>
								<code>
									<xsl:attribute name="code" namespace="" select="'RVI'"/>
									<xsl:attribute name="codeSystem" namespace="" select="'1.2.752.97.3.1.11'"/>
									<xsl:attribute name="codeSystemName" namespace="" select="'SLL Informationskomponentkoder'"/>
									<xsl:attribute name="displayName" namespace="" select="'Remissens versionsinformation'"/>
								</code>
								<entry>
									<observation>
										<xsl:attribute name="classCode" namespace="" select="'OBS'"/>
										<xsl:attribute name="moodCode" namespace="" select="'EVN'"/>
										<code>
											<xsl:attribute name="code" namespace="" select="'RV'"/>
											<xsl:attribute name="codeSystem" namespace="" select="'1.2.752.97.3.1.11'"/>
											<xsl:attribute name="codeSystemName" namespace="" select="'SLL Informationskomponentkoder'"/>
											<xsl:attribute name="displayName" namespace="" select="'Remissens version'"/>
										</code>
										<value>
											<xsl:attribute name="xsi:type" namespace="http://www.w3.org/2001/XMLSchema-instance" select="xs:QName('ST')"/>
											<xsl:sequence select="fn:string(ns2:requestVersionNumber)"/>
										</value>
									</observation>
								</entry>
							</section>
						</component>
					</structuredBody>
				</component>
			</xsl:for-each>
		</ClinicalDocument>
	</xsl:template>
</xsl:stylesheet>
