<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="urn:riv13606:13606RequestEHRExtract:v1" targetNamespace="urn:riv13606:13606RequestEHRExtract:v1">
	<wsdl:import namespace="urn:riv13606:13606RequestEHRExtract:v1" location="RIV13606_REQUEST_EHR_EXTRACT-1.0.wsdl"/>
	<wsdl:service name="RIV13606REQUEST_EHR_EXTRACT_Service">
		<wsdl:port name="RIV13606REQUEST_EHR_EXTRACT_Port" binding="tns:RIV13606REQUEST_EHR_EXTRACT_Binding">
			<soap:address location="https://localhost:19000/vardgivare-b/riv13606RequestEHRExtract" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
