<?xml version="1.0" encoding="UTF-8" ?>		
<wsdl:definitions name='GetBlocksForPatientInteraction' 
	xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' 
	xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' 
	xmlns:xs='http://www.w3.org/2001/XMLSchema' 
	xmlns:wsa='http://www.w3.org/2005/08/addressing' 
	xmlns:tjsr='urn:ehr:blocking:querying:GetBlocksForPatientResponder:1' 
	xmlns:tjsi='urn:ehr:blocking:querying:GetBlocksForPatientInitiator:1' 
	xmlns:tns='urn:ehr:blocking:querying:GetBlocksForPatient:1:rivtabp20' 
	targetNamespace='urn:ehr:blocking:querying:GetBlocksForPatient:1:rivtabp20'>
	
  <xs:annotation>
    <xs:documentation>
			 Tjänsteinteraktionens namn: GetBlocksForPatientInteraction
			 Beskrivning: Returnerar alla spärrar för en viss patient.
			 Revisioner: 2011-05-06: 1.0-beta
			 Tjänstedomän: blocking:querying
			 Tjänsteinteraktionstyp: Fråga-Svar
			 WS-profil: RIVTABP20
			 Förvaltas av: Inera AB
	</xs:documentation>
  </xs:annotation>
  
  <wsdl:types>
    <xs:schema targetNamespace='urn:ehr:blocking:querying:GetBlocksForPatient:1:rivtabp20'>
      <xs:import schemaLocation='GetBlocksForPatientResponder_1.0.xsd' namespace='urn:ehr:blocking:querying:GetBlocksForPatientResponder:1' />
      <xs:import schemaLocation='../../common/ws-addressing-1.0.xsd' namespace='http://www.w3.org/2005/08/addressing' />
    </xs:schema>
  </wsdl:types>
  
  <wsdl:message name='GetBlocksForPatientRequest'>
    <wsdl:part name='LogicalAddress' element='wsa:To'>
      <xs:annotation>
        <xs:documentation> Se tjänstedokumentationen för mer information om detta </xs:documentation>
      </xs:annotation>
    </wsdl:part>
    <wsdl:part name='parameters' element='tjsr:GetBlocksForPatient' />
  </wsdl:message>
  
  <wsdl:message name='GetBlocksForPatientResponse'>
    <wsdl:part name='parameters' element='tjsr:GetBlocksForPatientResponse' />
  </wsdl:message>
  
  <wsdl:portType name='GetBlocksForPatientResponderInterface'>
    <wsdl:operation name='GetBlocksForPatient'>
      <wsdl:input message='tns:GetBlocksForPatientRequest' />
      <wsdl:output message='tns:GetBlocksForPatientResponse' />
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name='GetBlocksForPatientResponderBinding' type='tns:GetBlocksForPatientResponderInterface'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='GetBlocksForPatient'>
      <soap:operation soapAction='urn:ehr:blocking:querying:GetBlocksForPatientResponder:1:GetBlocksForPatient' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:GetBlocksForPatientRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name='GetBlocksForPatientResponderService'>
    <wsdl:port name='GetBlocksForPatientResponderPort' binding='tns:GetBlocksForPatientResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>