//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:riv:itintegration:monitoring:PingForConfigurationResponder:1")]
public partial class PingForConfigurationType
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:riv:itintegration:monitoring:PingForConfigurationResponder:1")]
public partial class ConfigurationType
{
    
    private string nameField;
    
    private string valueField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}
namespace rivta_bp21_refapp_schemas.wsdl
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:riv:itintegration:monitoring:PingForConfiguration:1:rivtabp21", ConfigurationName="rivta_bp21_refapp_schemas.wsdl.PingForConfigurationResponderInterface")]
    public interface PingForConfigurationResponderInterface
    {
        
        // CODEGEN: Generating message contract since the operation PingForConfiguration is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:riv:itintegration:monitoring:PingForConfigurationResponder:1:PingForConfigura" +
            "tion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        rivta_bp21_refapp_schemas.wsdl.PingForConfigurationResponse PingForConfiguration(rivta_bp21_refapp_schemas.wsdl.PingForConfigurationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingForConfigurationRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:riv:itintegration:registry:1")]
        public string LogicalAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:riv:itintegration:monitoring:PingForConfigurationResponder:1", Order=0)]
        public PingForConfigurationType PingForConfiguration;
        
        public PingForConfigurationRequest()
        {
        }
        
        public PingForConfigurationRequest(string LogicalAddress, PingForConfigurationType PingForConfiguration)
        {
            this.LogicalAddress = LogicalAddress;
            this.PingForConfiguration = PingForConfiguration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingForConfigurationResponse", WrapperNamespace="urn:riv:itintegration:monitoring:PingForConfigurationResponder:1", IsWrapped=true)]
    public partial class PingForConfigurationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:riv:itintegration:monitoring:PingForConfigurationResponder:1", Order=0)]
        public string version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:riv:itintegration:monitoring:PingForConfigurationResponder:1", Order=1)]
        public string pingDateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:riv:itintegration:monitoring:PingForConfigurationResponder:1", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("configuration")]
        public ConfigurationType[] configuration;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public PingForConfigurationResponse()
        {
        }
        
        public PingForConfigurationResponse(string version, string pingDateTime, ConfigurationType[] configuration, System.Xml.XmlElement[] Any)
        {
            this.version = version;
            this.pingDateTime = pingDateTime;
            this.configuration = configuration;
            this.Any = Any;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface PingForConfigurationResponderInterfaceChannel : rivta_bp21_refapp_schemas.wsdl.PingForConfigurationResponderInterface, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PingForConfigurationResponderInterfaceClient : System.ServiceModel.ClientBase<rivta_bp21_refapp_schemas.wsdl.PingForConfigurationResponderInterface>, rivta_bp21_refapp_schemas.wsdl.PingForConfigurationResponderInterface
    {
        
        public PingForConfigurationResponderInterfaceClient()
        {
        }
        
        public PingForConfigurationResponderInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public PingForConfigurationResponderInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PingForConfigurationResponderInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PingForConfigurationResponderInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        rivta_bp21_refapp_schemas.wsdl.PingForConfigurationResponse rivta_bp21_refapp_schemas.wsdl.PingForConfigurationResponderInterface.PingForConfiguration(rivta_bp21_refapp_schemas.wsdl.PingForConfigurationRequest request)
        {
            return base.Channel.PingForConfiguration(request);
        }
        
        public string PingForConfiguration(string LogicalAddress, PingForConfigurationType PingForConfiguration1, out string pingDateTime, out ConfigurationType[] configuration, out System.Xml.XmlElement[] Any)
        {
            rivta_bp21_refapp_schemas.wsdl.PingForConfigurationRequest inValue = new rivta_bp21_refapp_schemas.wsdl.PingForConfigurationRequest();
            inValue.LogicalAddress = LogicalAddress;
            inValue.PingForConfiguration = PingForConfiguration1;
            rivta_bp21_refapp_schemas.wsdl.PingForConfigurationResponse retVal = ((rivta_bp21_refapp_schemas.wsdl.PingForConfigurationResponderInterface)(this)).PingForConfiguration(inValue);
            pingDateTime = retVal.pingDateTime;
            configuration = retVal.configuration;
            Any = retVal.Any;
            return retVal.version;
        }
    }
}
