<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions name='GetOrganizationsInteraction' 
	  xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' 
	  xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' 
	  xmlns:xs='http://www.w3.org/2001/XMLSchema' 
	  xmlns:wsa='http://www.w3.org/2005/08/addressing' 
	  xmlns:tjsr='urn:ehr:blocking:administration:GetOrganizationsResponder:1' 
	  xmlns:tjsi='urn:ehr:blocking:administration:GetOrganizationsInitiator:1' 
	  xmlns:tns='urn:ehr:blocking:administration:GetOrganizations:1:rivtabp20' 
	  targetNamespace='urn:ehr:blocking:administration:GetOrganizations:1:rivtabp20'>
	  
  <xs:annotation>
    <xs:documentation>
			 Tjänsteinteraktionens namn: GetOrganizationsInteraction
			 Beskrivning: Hämta organisationsomfång för aktuell spärrtjänst.
			 Revisioner: 2011-05-06: 1.0-beta
			 Tjänstedomän: blocking:administration
			 Tjänsteinteraktionstyp: Fråga-Svar
			 WS-profil: RIVTABP20
			 Förvaltas av: Inera AB
	</xs:documentation>
  </xs:annotation>
  
  <wsdl:types>
    <xs:schema targetNamespace='urn:ehr:blocking:administration:GetOrganizations:1:rivtabp20'>
      <xs:import schemaLocation='GetOrganizationsResponder_1.0.xsd' namespace='urn:ehr:blocking:administration:GetOrganizationsResponder:1' />
      <xs:import schemaLocation='../../common/ws-addressing-1.0.xsd' namespace='http://www.w3.org/2005/08/addressing' />
    </xs:schema>
  </wsdl:types>
  
  <wsdl:message name='GetOrganizationsRequest'>
    <wsdl:part name='LogicalAddress' element='wsa:To'>
      <xs:annotation>
        <xs:documentation> Se tjänstedokumentationen för mer information om detta </xs:documentation>
      </xs:annotation>
    </wsdl:part>
    <wsdl:part name='parameters' element='tjsr:GetOrganizations' />
  </wsdl:message>
  
  <wsdl:message name='GetOrganizationsResponse'>
    <wsdl:part name='parameters' element='tjsr:GetOrganizationsResponse' />
  </wsdl:message>
  
  <wsdl:portType name='GetOrganizationsResponderInterface'>
    <wsdl:operation name='GetOrganizations'>
      <wsdl:input message='tns:GetOrganizationsRequest' />
      <wsdl:output message='tns:GetOrganizationsResponse' />
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name='GetOrganizationsResponderBinding' type='tns:GetOrganizationsResponderInterface'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='GetOrganizations'>
      <soap:operation soapAction='urn:ehr:blocking:administration:GetOrganizationsResponder:1:GetOrganizations' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:GetOrganizationsRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name='GetOrganizationsResponderService'>
    <wsdl:port name='GetOrganizationsResponderPort' binding='tns:GetOrganizationsResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>