<?xml version="1.0" encoding="UTF-8" ?>		
<wsdl:definitions name='CheckBlocksInteraction' 
	  xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' 
	  xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' 
	  xmlns:xs='http://www.w3.org/2001/XMLSchema' 
	  xmlns:wsa='http://www.w3.org/2005/08/addressing' 
	  xmlns:tjsr='urn:ehr:blocking:accesscontrol:CheckBlocksResponder:1' 
	  xmlns:tjsi='urn:ehr:blocking:accesscontrol:CheckBlocksInitiator:1' 
	  xmlns:tns='urn:ehr:blocking:accesscontrol:CheckBlocks:1:rivtabp20' 
	  targetNamespace='urn:ehr:blocking:accesscontrol:CheckBlocks:1:rivtabp20'>
	  
  <xs:annotation>
    <xs:documentation>
			 Tjänsteinteraktionens namn: CheckBlocksInteraction
			 Beskrivning: Kontrollera om given information är spärrad.
			 Revisioner: 2011-05-06: 1.0-beta
			 Tjänstedomän: blocking:accesscontrol
			 Tjänsteinteraktionstyp: Fråga-Svar
			 WS-profil: RIVTABP20
			 Förvaltas av: Inera AB
	</xs:documentation>
  </xs:annotation>
  
  <wsdl:types>
    <xs:schema targetNamespace='urn:ehr:blocking:accesscontrol:CheckBlocks:1:rivtabp20'>
      <xs:import schemaLocation='CheckBlocksResponder_1.0.xsd' namespace='urn:ehr:blocking:accesscontrol:CheckBlocksResponder:1' />
      <xs:import schemaLocation='../../common/ws-addressing-1.0.xsd' namespace='http://www.w3.org/2005/08/addressing' />
    </xs:schema>
  </wsdl:types>
  
  <wsdl:message name='CheckBlocksRequest'>
    <wsdl:part name='LogicalAddress' element='wsa:To'>
      <xs:annotation>
        <xs:documentation> Se tjänstedokumentationen för mer information om detta </xs:documentation>
      </xs:annotation>
    </wsdl:part>
    <wsdl:part name='parameters' element='tjsr:CheckBlocks' />
  </wsdl:message>
  
  <wsdl:message name='CheckBlocksResponse'>
    <wsdl:part name='parameters' element='tjsr:CheckBlocksResponse' />
  </wsdl:message>
  
  <wsdl:portType name='CheckBlocksResponderInterface'>
    <wsdl:operation name='CheckBlocks'>
      <wsdl:input message='tns:CheckBlocksRequest' />
      <wsdl:output message='tns:CheckBlocksResponse' />
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name='CheckBlocksResponderBinding' type='tns:CheckBlocksResponderInterface'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='CheckBlocks'>
      <soap:operation soapAction='urn:ehr:blocking:accesscontrol:CheckBlocksResponder:1:CheckBlocks' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:CheckBlocksRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name='CheckBlocksResponderService'>
    <wsdl:port name='CheckBlocksResponderPort' binding='tns:CheckBlocksResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>