<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions name='GetExtendedBlocksForPatientInteraction' 
	  xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' 
	  xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' 
	  xmlns:xs='http://www.w3.org/2001/XMLSchema' 
	  xmlns:wsa='http://www.w3.org/2005/08/addressing' 
	  xmlns:tjsr='urn:ehr:blocking:administration:GetExtendedBlocksForPatientResponder:1' 
	  xmlns:tjsi='urn:ehr:blocking:administration:GetExtendedBlocksForPatientInitiator:1' 
	  xmlns:tns='urn:ehr:blocking:administration:GetExtendedBlocksForPatient:1:rivtabp20' 
	  targetNamespace='urn:ehr:blocking:administration:GetExtendedBlocksForPatient:1:rivtabp20'>
	  
  <xs:annotation>
    <xs:documentation>
			 Tjänsteinteraktionens namn: GetExtendedBlocksForPatientInteraction
			 Beskrivning: Hämta utökade spärrar för given patient.
			 Revisioner: 2011-08-23: 1.0
			 Tjänstedomän: blocking:administration
			 Tjänsteinteraktionstyp: Fråga-Svar
			 WS-profil: RIVTABP20
			 Förvaltas av: Inera AB
			 </xs:documentation>
  </xs:annotation>
  
  <wsdl:types>
    <xs:schema targetNamespace='urn:ehr:blocking:administration:GetExtendedBlocksForPatient:1:rivtabp20'>
      <xs:import schemaLocation='GetExtendedBlocksForPatientResponder_1.0.xsd' namespace='urn:ehr:blocking:administration:GetExtendedBlocksForPatientResponder:1' />
      <xs:import schemaLocation='../../common/ws-addressing-1.0.xsd' namespace='http://www.w3.org/2005/08/addressing' />
    </xs:schema>
  </wsdl:types>
  
  <wsdl:message name='GetExtendedBlocksForPatientRequest'>
    <wsdl:part name='LogicalAddress' element='wsa:To'>
      <xs:annotation>
        <xs:documentation> Se tjänstedokumentationen för mer information om detta </xs:documentation>
      </xs:annotation>
    </wsdl:part>
    <wsdl:part name='parameters' element='tjsr:GetExtendedBlocksForPatient' />
  </wsdl:message>
  
  <wsdl:message name='GetExtendedBlocksForPatientResponse'>
    <wsdl:part name='parameters' element='tjsr:GetExtendedBlocksForPatientResponse' />
  </wsdl:message>
  
  <wsdl:portType name='GetExtendedBlocksForPatientResponderInterface'>
    <wsdl:operation name='GetExtendedBlocksForPatient'>
      <wsdl:input message='tns:GetExtendedBlocksForPatientRequest' />
      <wsdl:output message='tns:GetExtendedBlocksForPatientResponse' />
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name='GetExtendedBlocksForPatientResponderBinding' type='tns:GetExtendedBlocksForPatientResponderInterface'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='GetExtendedBlocksForPatient'>
      <soap:operation soapAction='urn:ehr:blocking:administration:GetExtendedBlocksForPatientResponder:1:GetExtendedBlocksForPatient' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:GetExtendedBlocksForPatientRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name='GetExtendedBlocksForPatientResponderService'>
    <wsdl:port name='GetExtendedBlocksForPatientResponderPort' binding='tns:GetExtendedBlocksForPatientResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>